scrape_configs:
  - job_name: 'flask_application'
    static_configs:
      - targets: ['localhost:8000']  # Puerto donde Flask expone las m√©tricas

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # Puerto por defecto de Node Exporter